### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_alpha: 16
lora_target: all

### dataset
dataset: gsm8k
template: qwen
cutoff_len: 1024
max_samples: 1024
preprocessing_num_workers: 8
dataloader_num_workers: 2

### output
output_dir: saves/qwen2_5-7b/lora/gsm8k_sft_smoke_2gpu
logging_steps: 5
save_steps: 100
plot_loss: false
overwrite_output_dir: true
save_only_model: true
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 2.0e-4
num_train_epochs: 1.0
max_steps: 20
lr_scheduler_type: cosine
warmup_steps: 2
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: no
